name: capstone_porj
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  http: ^1.3.0
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  flutter_webrtc: ^0.13.1+hotfix.1
  socket_io_client: ^3.1.1
  permission_handler: ^12.0.0
  path_provider: ^2.1.5

  # ✅ 추가된 누락 패키지들
  flutter_dotenv: ^5.1.0
  geolocator: ^10.1.0
  flutter_sound: ^9.2.13
  google_mlkit_face_detection: ^0.10.0
  image: ^4.1.7
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/default_mask.png
    - .env
